[pytest]

addopts =
    -v
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure

testpaths =
    tests

python_files =
    test_*.py

markers =
    smoke
    regression

log_cli = true
log_cli_level = INFO